### A. Creating Series and DataFrames

In [70]:
# step 1: import panda package
import pandas as pd

# step 2 : Define a list
data = [1, 2, 3, 4, 5, 6, 7 ,8, 9, 10]

# step 3: create the series
series = pd.Series(data)

# view the created series
series.head(10)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [71]:
# confirming we created a pandas series
type(series)

pandas.core.series.Series

In [72]:
# creating a series using the same list, but  adding custom serial numbers
series2 = pd.Series(data, index= ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"])
series2.head()

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [73]:
# creating a series using python dictionary 
data2 = {"a": 10, "b": 20, "c": 30}

# creating the series
series3= pd.Series(data2)
series.head()

0    1
1    2
2    3
3    4
4    5
dtype: int64


**Hands on practice**:
1. Create a bucket list of 6 items. Convert the list to pandas series and define index for it using alphabets.
2. Create a simple python dictionary of your biodata with 5 keys and their corresponding values. Convert the dictionary into a pandas series.

Question 1

In [74]:
# bucket list of 6 items
item_list =["shoe", "bag", "stone", "fish", "cheese", "cherry"]

# converting the bucket list to panda series and defining alphabets as the index
items_series = pd.Series(item_list, index= ["a", "b", "c", "d", "e", "f"])

items_series.head(6)

a      shoe
b       bag
c     stone
d      fish
e    cheese
f    cherry
dtype: object

Question 2

In [75]:
# creating the python dictionary of  biodata with 5keys
bio_data= {"Name": "Dominion James", "Track":"AI Engineering", "Age": 90, "Gender":"Female", "School": "Aptech"}

# converting the biodata dictionary to panda series
bio_data_series = pd.Series(bio_data)


bio_data_series.head()

Name      Dominion James
Track     AI Engineering
Age                   90
Gender            Female
School            Aptech
dtype: object

**Creating a DataFrame**

In [76]:
# creating a data frame

# step1: import pandas

import pandas as pd

# define the data using dictionary that is having values as a list

data = {
    "Name": ["Chris", "Ayo", "Chisom"],
    "Age": [26, 24, 22],
    "Home_Town": ["Benin", "Ibadan", "Enugu"]
}

# creating the dataframe using "df" as short for dataframe
df= pd.DataFrame(data, index=[1, 2, 3])
df.head()

     Name  Age Home_Town
1   Chris   26     Benin
2     Ayo   24    Ibadan
3  Chisom   22     Enugu

In [77]:
# using list of dictionaries
data2 =[
    {"Name": "Chris", "Age": 26, "Home Town": "Benin"},
    {"Name": "Ayo", "Age": 24, "Home Town": "Ibadan"},
    {"Name": "Chisom", "Age": 22, "Home Town": "Enugu"}
]
df2 = pd.DataFrame(data2, index=[1, 2, 3])
df2.head()

     Name  Age Home Town
1   Chris   26     Benin
2     Ayo   24    Ibadan
3  Chisom   22     Enugu

In [78]:
# using list of list
data3 =[
       ["Chris", 26, "Benin"],
       ["Ayo", 24, "Ibadan"],
       ["Chisom", 22, "Enugu"]
]

df3 = pd.DataFrame(data3, columns=["Name", "Age", "Home Town"], index=[1, 2, 3])
df3.head()

     Name  Age Home Town
1   Chris   26     Benin
2     Ayo   24    Ibadan
3  Chisom   22     Enugu

In [79]:
# printing the types to be sure we have defined dataframes
print(type(df))
print(type(df2))
print(type(df3))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>

**Data Input and Output**

In [80]:
import pandas as pd
import csv

# To read in dataset (csv) we use
df = pd.read_csv("bio_data.csv")

**Data Inspection and Exploration**

In [81]:
# To view the first 5 rows
df.head()

# To view the last 5 rows
df.tail()

# To check the information about the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Timestamp     34 non-null     object
 1   First Name    34 non-null     object
 2   Last Name     34 non-null     object
 3   Course Track  34 non-null     object
 4   City          34 non-null     object
 5   Gender        34 non-null     object
 6   Seat Number   34 non-null     object
 7   PC-Make       34 non-null     object
 8   PC - OS       34 non-null     object
 9   Feedback      34 non-null     object
dtypes: object(10)
memory usage: 2.8+ KB

In [82]:
# To show the statistical summary
df.describe()

# To check the dimension of the dataset
df.shape

# To check the column names
df.columns

# This calls all the data in the dataset
df

,Timestamp,First Name,Last Name,Course Track,City,Gender,Seat Number,PC-Make,PC - OS,Feedback
0,2025/09/11 12:55:34 PM GMT+1,Peter,Okonmah,AI,Ogun,Male,28,MACBOOK,Mac OS,non
1,2025/09/11 12:56:11 PM GMT+1,Toyeebat,Nababa,AI,Abeokuta,Female,24,HP,Windows,Excellent
2,2025/09/11 12:57:08 PM GMT+1,Perpetual,Meninwa,AI,Lagos,Female,22,HP,Windows,Thank you so much for the opportunity.
3,2025/09/11 12:57:56 PM GMT+1,Mahfuz,Abdulhameed,AI,Abeokuta,Male,44,HP,Windows,Amazing Shit
4,2025/09/11 12:58:41 PM GMT+1,Divine,Gbadamosi,AI,Abeokuta,Male,35,DELL,Windows,Brain Racking
5,2025/09/11 12:58:55 PM GMT+1,Abdulmalik,Adedotun,AI,Abeokuta,Male,200,HP,Windows,Enjoying the course so far
6,2025/09/11 12:58:55 PM GMT+1,Naheemot,Adebiyi,AI,Abeokuta,Female,32,DELL,Windows,Grateful for the opportunity to be here.
7,2025/09/11 12:59:00 PM GMT+1,Kanyisola,Fagbayi,AI;Data Science,Lagos,Female,00082,HP,Windows,One chin chin for you for this form
8,2025/09/11 12:59:16 PM GMT+1,Blessing,James,Cyber Security,Nairobi,Female,45678,HP,Windows,Thanks for creating the form.
9,2025/09/11 12:59:28 PM GMT+1,Hannah,Tanimola,AI,Abeokuta,Male,30,HP,Windows,On God
10,2025/09/11 12:59:41 PM GMT+1,Deborah,Adelegan,AI;Data Science,Abeokuta,Female,001,HP,Windows,None for now
11,2025/09/11 12:59:43 PM GMT+1,Esther,Kudoro,AI,Abeokuta,Female,1,HP,Windows,Chill
12,2025/09/11 1:00:03 PM GMT+1,Opeyemi,Odejimi,Cloud Computing,Abeokuta,Male,38,HP,Linux,Na wa
13,2025/09/11 1:00:13 PM GMT+1,Olasunkanmi,Rasak,AI,Kobape,Male,3,HP,Windows,My gratitude to the sponsor of this program an...
14,2025/09/11 1:00:27 PM GMT+1,Saheed,Olayinka,AI;Data Science;Web Dev,Abeokuta,Male,29,HP,Windows,None for now
15,2025/09/11 1:00:31 PM GMT+1,Kehinde,Akindele,Cloud Computing,Abeokuta,Male,54,Gateway,Windows,Great
16,2025/09/11 1:00:43 PM GMT+1,Oluwole,Oludayo,AI,Abeokuta,Male,09,HP,Windows,Good training to attend
17,2025/09/11 1:00:49 PM GMT+1,Samuel,Oyewusi,Web Dev,Lagos,Male,15,HP,Windows,Satisfactory
18,2025/09/11 1:00:54 PM GMT+1,Ademola,Akinrinde,AI,Abeokuta,Male,100,MACBOOK,Mac OS,Awesome shit\n\n
19,2025/09/11 1:01:31 PM GMT+1,Victor,Ademuyiwa,AI,kobape,Male,2,ASUS,Windows,Feels good
20,2025/09/11 1:01:44 PM GMT+1,Sherif,Okemakinde,AI,Abeokuta,Male,27,HP,Windows,Form filled
21,2025/09/11 1:01:46 PM GMT+1,Ayuba,Raji,AI,Abeokuta,Male,26,HP,Windows,None for now
22,2025/09/11 1:01:54 PM GMT+1,Hamid,Jimoh,AI,Ibadan,Male,299,DELL,Windows,I am curious
23,2025/09/11 1:02:28 PM GMT+1,Olajide,Abioye,AI,Abeokuta,Male,5,HP,Windows,"So far, i getting to familarize myself with nu..."
24,2025/09/11 1:02:49 PM GMT+1,Solomon,Olaiya,AI,Abeokuta,Male,16,MACBOOK,Mac OS,Delighted learning here
25,2025/09/11 1:02:56 PM GMT+1,Oluwadamilare,Bello,AI,Sango,Male,373,DELL;HP;LENOVO;MACBOOK;ASUS;,Mac OS,Coding is interesting when you understand
26,2025/09/11 1:02:59 PM GMT+1,Oluwaseyi,Egunjobi,Cloud Computing,Cape Town,Male,dirty,MACBOOK,Mac OS,Nice to meet you all
27,2025/09/11 1:03:12 PM GMT+1,Adeoye,Mary,AI,abeokuta,Female,15,LENOVO,Windows,Still processing
28,2025/09/11 1:03:36 PM GMT+1,Babatunde,Rahmon,AI,Abeokuta,Male,20,none,Windows,i actually have a pc that has a very low stora...
29,2025/09/11 1:06:03 PM GMT+1,Samuel,Dasaolu,AI,Abeokuta,Male,100,HP;MACBOOK,Linux,"Good so far, i guess"
30,2025/09/11 1:06:48 PM GMT+1,Gabriel,Bamgbose,AI,Abeokuta,Male,2,HP,Windows,Good
31,2025/09/11 1:10:16 PM GMT+1,Ridwanullah,Osho,AI;Cyber Security;Data Science,Abeokuta,Male,45,DELL,Windows,IT IS WHAT IT IS !!!
32,2025/09/11 1:11:39 PM GMT+1,Oluwapelumi,Adenuga,Web Dev,Abeokuta,Male,36,HP,Windows,live yours
33,2025/09/11 1:18:15 PM GMT+1,Michael,Osisami,AI,Abeokuta,Male,12,DELL;HP,Windows,Nil

### D. Data Cleaning

 Data cleaning involves identifying and handling errors or inconsistencies in your dataset. Later in this course, data cleaning would be handled in datails.

In [83]:
import pandas as pd
import csv

# To read in dataset (csv) we use
df = pd.read_csv("bio_data.csv")

# handling missing values
df.isna()
df.isnull()

# check the total number of all missing values
df.isna().sum()

# to fill up missing values 
# df.fillna()

# to drop missing values
df.dropna()

,Timestamp,First Name,Last Name,Course Track,City,Gender,Seat Number,PC-Make,PC - OS,Feedback
0,2025/09/11 12:55:34 PM GMT+1,Peter,Okonmah,AI,Ogun,Male,28,MACBOOK,Mac OS,non
1,2025/09/11 12:56:11 PM GMT+1,Toyeebat,Nababa,AI,Abeokuta,Female,24,HP,Windows,Excellent
2,2025/09/11 12:57:08 PM GMT+1,Perpetual,Meninwa,AI,Lagos,Female,22,HP,Windows,Thank you so much for the opportunity.
3,2025/09/11 12:57:56 PM GMT+1,Mahfuz,Abdulhameed,AI,Abeokuta,Male,44,HP,Windows,Amazing Shit
4,2025/09/11 12:58:41 PM GMT+1,Divine,Gbadamosi,AI,Abeokuta,Male,35,DELL,Windows,Brain Racking
5,2025/09/11 12:58:55 PM GMT+1,Abdulmalik,Adedotun,AI,Abeokuta,Male,200,HP,Windows,Enjoying the course so far
6,2025/09/11 12:58:55 PM GMT+1,Naheemot,Adebiyi,AI,Abeokuta,Female,32,DELL,Windows,Grateful for the opportunity to be here.
7,2025/09/11 12:59:00 PM GMT+1,Kanyisola,Fagbayi,AI;Data Science,Lagos,Female,00082,HP,Windows,One chin chin for you for this form
8,2025/09/11 12:59:16 PM GMT+1,Blessing,James,Cyber Security,Nairobi,Female,45678,HP,Windows,Thanks for creating the form.
9,2025/09/11 12:59:28 PM GMT+1,Hannah,Tanimola,AI,Abeokuta,Male,30,HP,Windows,On God
10,2025/09/11 12:59:41 PM GMT+1,Deborah,Adelegan,AI;Data Science,Abeokuta,Female,001,HP,Windows,None for now
11,2025/09/11 12:59:43 PM GMT+1,Esther,Kudoro,AI,Abeokuta,Female,1,HP,Windows,Chill
12,2025/09/11 1:00:03 PM GMT+1,Opeyemi,Odejimi,Cloud Computing,Abeokuta,Male,38,HP,Linux,Na wa
13,2025/09/11 1:00:13 PM GMT+1,Olasunkanmi,Rasak,AI,Kobape,Male,3,HP,Windows,My gratitude to the sponsor of this program an...
14,2025/09/11 1:00:27 PM GMT+1,Saheed,Olayinka,AI;Data Science;Web Dev,Abeokuta,Male,29,HP,Windows,None for now
15,2025/09/11 1:00:31 PM GMT+1,Kehinde,Akindele,Cloud Computing,Abeokuta,Male,54,Gateway,Windows,Great
16,2025/09/11 1:00:43 PM GMT+1,Oluwole,Oludayo,AI,Abeokuta,Male,09,HP,Windows,Good training to attend
17,2025/09/11 1:00:49 PM GMT+1,Samuel,Oyewusi,Web Dev,Lagos,Male,15,HP,Windows,Satisfactory
18,2025/09/11 1:00:54 PM GMT+1,Ademola,Akinrinde,AI,Abeokuta,Male,100,MACBOOK,Mac OS,Awesome shit\n\n
19,2025/09/11 1:01:31 PM GMT+1,Victor,Ademuyiwa,AI,kobape,Male,2,ASUS,Windows,Feels good
20,2025/09/11 1:01:44 PM GMT+1,Sherif,Okemakinde,AI,Abeokuta,Male,27,HP,Windows,Form filled
21,2025/09/11 1:01:46 PM GMT+1,Ayuba,Raji,AI,Abeokuta,Male,26,HP,Windows,None for now
22,2025/09/11 1:01:54 PM GMT+1,Hamid,Jimoh,AI,Ibadan,Male,299,DELL,Windows,I am curious
23,2025/09/11 1:02:28 PM GMT+1,Olajide,Abioye,AI,Abeokuta,Male,5,HP,Windows,"So far, i getting to familarize myself with nu..."
24,2025/09/11 1:02:49 PM GMT+1,Solomon,Olaiya,AI,Abeokuta,Male,16,MACBOOK,Mac OS,Delighted learning here
25,2025/09/11 1:02:56 PM GMT+1,Oluwadamilare,Bello,AI,Sango,Male,373,DELL;HP;LENOVO;MACBOOK;ASUS;,Mac OS,Coding is interesting when you understand
26,2025/09/11 1:02:59 PM GMT+1,Oluwaseyi,Egunjobi,Cloud Computing,Cape Town,Male,dirty,MACBOOK,Mac OS,Nice to meet you all
27,2025/09/11 1:03:12 PM GMT+1,Adeoye,Mary,AI,abeokuta,Female,15,LENOVO,Windows,Still processing
28,2025/09/11 1:03:36 PM GMT+1,Babatunde,Rahmon,AI,Abeokuta,Male,20,none,Windows,i actually have a pc that has a very low stora...
29,2025/09/11 1:06:03 PM GMT+1,Samuel,Dasaolu,AI,Abeokuta,Male,100,HP;MACBOOK,Linux,"Good so far, i guess"
30,2025/09/11 1:06:48 PM GMT+1,Gabriel,Bamgbose,AI,Abeokuta,Male,2,HP,Windows,Good
31,2025/09/11 1:10:16 PM GMT+1,Ridwanullah,Osho,AI;Cyber Security;Data Science,Abeokuta,Male,45,DELL,Windows,IT IS WHAT IT IS !!!
32,2025/09/11 1:11:39 PM GMT+1,Oluwapelumi,Adenuga,Web Dev,Abeokuta,Male,36,HP,Windows,live yours
33,2025/09/11 1:18:15 PM GMT+1,Michael,Osisami,AI,Abeokuta,Male,12,DELL;HP,Windows,Nil

Finding and Handling Duplicates

In [84]:
# to check if there are duplicates
df.duplicated()

# for dropping duplicate values
df.drop_duplicates()

,Timestamp,First Name,Last Name,Course Track,City,Gender,Seat Number,PC-Make,PC - OS,Feedback
0,2025/09/11 12:55:34 PM GMT+1,Peter,Okonmah,AI,Ogun,Male,28,MACBOOK,Mac OS,non
1,2025/09/11 12:56:11 PM GMT+1,Toyeebat,Nababa,AI,Abeokuta,Female,24,HP,Windows,Excellent
2,2025/09/11 12:57:08 PM GMT+1,Perpetual,Meninwa,AI,Lagos,Female,22,HP,Windows,Thank you so much for the opportunity.
3,2025/09/11 12:57:56 PM GMT+1,Mahfuz,Abdulhameed,AI,Abeokuta,Male,44,HP,Windows,Amazing Shit
4,2025/09/11 12:58:41 PM GMT+1,Divine,Gbadamosi,AI,Abeokuta,Male,35,DELL,Windows,Brain Racking
5,2025/09/11 12:58:55 PM GMT+1,Abdulmalik,Adedotun,AI,Abeokuta,Male,200,HP,Windows,Enjoying the course so far
6,2025/09/11 12:58:55 PM GMT+1,Naheemot,Adebiyi,AI,Abeokuta,Female,32,DELL,Windows,Grateful for the opportunity to be here.
7,2025/09/11 12:59:00 PM GMT+1,Kanyisola,Fagbayi,AI;Data Science,Lagos,Female,00082,HP,Windows,One chin chin for you for this form
8,2025/09/11 12:59:16 PM GMT+1,Blessing,James,Cyber Security,Nairobi,Female,45678,HP,Windows,Thanks for creating the form.
9,2025/09/11 12:59:28 PM GMT+1,Hannah,Tanimola,AI,Abeokuta,Male,30,HP,Windows,On God
10,2025/09/11 12:59:41 PM GMT+1,Deborah,Adelegan,AI;Data Science,Abeokuta,Female,001,HP,Windows,None for now
11,2025/09/11 12:59:43 PM GMT+1,Esther,Kudoro,AI,Abeokuta,Female,1,HP,Windows,Chill
12,2025/09/11 1:00:03 PM GMT+1,Opeyemi,Odejimi,Cloud Computing,Abeokuta,Male,38,HP,Linux,Na wa
13,2025/09/11 1:00:13 PM GMT+1,Olasunkanmi,Rasak,AI,Kobape,Male,3,HP,Windows,My gratitude to the sponsor of this program an...
14,2025/09/11 1:00:27 PM GMT+1,Saheed,Olayinka,AI;Data Science;Web Dev,Abeokuta,Male,29,HP,Windows,None for now
15,2025/09/11 1:00:31 PM GMT+1,Kehinde,Akindele,Cloud Computing,Abeokuta,Male,54,Gateway,Windows,Great
16,2025/09/11 1:00:43 PM GMT+1,Oluwole,Oludayo,AI,Abeokuta,Male,09,HP,Windows,Good training to attend
17,2025/09/11 1:00:49 PM GMT+1,Samuel,Oyewusi,Web Dev,Lagos,Male,15,HP,Windows,Satisfactory
18,2025/09/11 1:00:54 PM GMT+1,Ademola,Akinrinde,AI,Abeokuta,Male,100,MACBOOK,Mac OS,Awesome shit\n\n
19,2025/09/11 1:01:31 PM GMT+1,Victor,Ademuyiwa,AI,kobape,Male,2,ASUS,Windows,Feels good
20,2025/09/11 1:01:44 PM GMT+1,Sherif,Okemakinde,AI,Abeokuta,Male,27,HP,Windows,Form filled
21,2025/09/11 1:01:46 PM GMT+1,Ayuba,Raji,AI,Abeokuta,Male,26,HP,Windows,None for now
22,2025/09/11 1:01:54 PM GMT+1,Hamid,Jimoh,AI,Ibadan,Male,299,DELL,Windows,I am curious
23,2025/09/11 1:02:28 PM GMT+1,Olajide,Abioye,AI,Abeokuta,Male,5,HP,Windows,"So far, i getting to familarize myself with nu..."
24,2025/09/11 1:02:49 PM GMT+1,Solomon,Olaiya,AI,Abeokuta,Male,16,MACBOOK,Mac OS,Delighted learning here
25,2025/09/11 1:02:56 PM GMT+1,Oluwadamilare,Bello,AI,Sango,Male,373,DELL;HP;LENOVO;MACBOOK;ASUS;,Mac OS,Coding is interesting when you understand
26,2025/09/11 1:02:59 PM GMT+1,Oluwaseyi,Egunjobi,Cloud Computing,Cape Town,Male,dirty,MACBOOK,Mac OS,Nice to meet you all
27,2025/09/11 1:03:12 PM GMT+1,Adeoye,Mary,AI,abeokuta,Female,15,LENOVO,Windows,Still processing
28,2025/09/11 1:03:36 PM GMT+1,Babatunde,Rahmon,AI,Abeokuta,Male,20,none,Windows,i actually have a pc that has a very low stora...
29,2025/09/11 1:06:03 PM GMT+1,Samuel,Dasaolu,AI,Abeokuta,Male,100,HP;MACBOOK,Linux,"Good so far, i guess"
30,2025/09/11 1:06:48 PM GMT+1,Gabriel,Bamgbose,AI,Abeokuta,Male,2,HP,Windows,Good
31,2025/09/11 1:10:16 PM GMT+1,Ridwanullah,Osho,AI;Cyber Security;Data Science,Abeokuta,Male,45,DELL,Windows,IT IS WHAT IT IS !!!
32,2025/09/11 1:11:39 PM GMT+1,Oluwapelumi,Adenuga,Web Dev,Abeokuta,Male,36,HP,Windows,live yours
33,2025/09/11 1:18:15 PM GMT+1,Michael,Osisami,AI,Abeokuta,Male,12,DELL;HP,Windows,Nil

Correcting Data Types

In pandas there are two main types of datatypes, "integer" and "Object"


```c

df types
```

To convert the type of perform type casting, you use

```c
df.astype() # this takes in the datatype you want to convert it to as an argument
```

When working with time or time series data its important to convert the time to pandas recognized time using

```c
pd.to_datetime() # takes in the data column as an argument
```

In [85]:
# To change the data type of the seat number column and replacing the dirty value
df["Seat Number"]= df["Seat Number"].replace("dirty", 35)

# .astype() takes in the datatype you want to convert it to as an argument
df["Seat Number"]= df["Seat Number"].astype(int)
df["Seat Number"]

0        28
1        24
2        22
3        44
4        35
5       200
6        32
7        82
8     45678
9        30
10        1
11        1
12       38
13        3
14       29
15       54
16        9
17       15
18      100
19        2
20       27
21       26
22      299
23        5
24       16
25      373
26       35
27       15
28       20
29      100
30        2
31       45
32       36
33       12
Name: Seat Number, dtype: int64

In [86]:
# To change the data type of the Timestamp column
df["Timestamp"]= pd.to_datetime(df["Timestamp"]) # takes in the data column as an argument
df["Timestamp"]
# df.columns

C:\Users\ncc84\AppData\Local\Temp\ipykernel_5996\454121679.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Timestamp"]= pd.to_datetime(df["Timestamp"]) # takes in the data column as an argument

0    2025-09-11 12:55:34-01:00
1    2025-09-11 12:56:11-01:00
2    2025-09-11 12:57:08-01:00
3    2025-09-11 12:57:56-01:00
4    2025-09-11 12:58:41-01:00
5    2025-09-11 12:58:55-01:00
6    2025-09-11 12:58:55-01:00
7    2025-09-11 12:59:00-01:00
8    2025-09-11 12:59:16-01:00
9    2025-09-11 12:59:28-01:00
10   2025-09-11 12:59:41-01:00
11   2025-09-11 12:59:43-01:00
12   2025-09-11 13:00:03-01:00
13   2025-09-11 13:00:13-01:00
14   2025-09-11 13:00:27-01:00
15   2025-09-11 13:00:31-01:00
16   2025-09-11 13:00:43-01:00
17   2025-09-11 13:00:49-01:00
18   2025-09-11 13:00:54-01:00
19   2025-09-11 13:01:31-01:00
20   2025-09-11 13:01:44-01:00
21   2025-09-11 13:01:46-01:00
22   2025-09-11 13:01:54-01:00
23   2025-09-11 13:02:28-01:00
24   2025-09-11 13:02:49-01:00
25   2025-09-11 13:02:56-01:00
26   2025-09-11 13:02:59-01:00
27   2025-09-11 13:03:12-01:00
28   2025-09-11 13:03:36-01:00
29   2025-09-11 13:06:03-01:00
30   2025-09-11 13:06:48-01:00
31   2025-09-11 13:10:16-01:00
32   2025-09-11 13:11:39-01:00
33   2025-09-11 13:18:15-01:00
Name: Timestamp, dtype: datetime64[ns, UTC-01:00]

In [87]:
# to check data type of all the columns
df.dtypes

Timestamp       datetime64[ns, UTC-01:00]
First Name                         object
Last Name                          object
Course Track                       object
City                               object
Gender                             object
Seat Number                         int64
PC-Make                            object
PC - OS                            object
Feedback                           object
dtype: object

### E. Data Selection and Filtering

Viewing data column

In [88]:
# bio_data_columns =["First_Name", "Last_Name", "Course_Track","City", "Gender", "Seat Number", "PC_Make","PC_OS" ]
df.columns

Index(['Timestamp', 'First Name', 'Last Name', 'Course Track', 'City',
       'Gender', 'Seat Number', 'PC-Make', 'PC - OS', 'Feedback'],
      dtype='object')

Columns Selection

In [89]:
# selecting a single columnn
df["Gender"]

# Looking through a single column using dot
df.Gender

0       Male
1     Female
2     Female
3       Male
4       Male
5       Male
6     Female
7     Female
8     Female
9       Male
10    Female
11    Female
12      Male
13      Male
14      Male
15      Male
16      Male
17      Male
18      Male
19      Male
20      Male
21      Male
22      Male
23      Male
24      Male
25      Male
26      Male
27    Female
28      Male
29      Male
30      Male
31      Male
32      Male
33      Male
Name: Gender, dtype: object

In [90]:
# selecting multiple columnns
df[["Gender", "Last Name", "First Name"]]
df[["Gender", "City", "First Name"]]

    Gender       City     First Name
0     Male       Ogun          Peter
1   Female   Abeokuta       Toyeebat
2   Female      Lagos      Perpetual
3     Male   Abeokuta         Mahfuz
4     Male   Abeokuta         Divine
5     Male   Abeokuta     Abdulmalik
6   Female   Abeokuta       Naheemot
7   Female      Lagos      Kanyisola
8   Female    Nairobi       Blessing
9     Male   Abeokuta         Hannah
10  Female   Abeokuta        Deborah
11  Female   Abeokuta         Esther
12    Male   Abeokuta        Opeyemi
13    Male     Kobape    Olasunkanmi
14    Male   Abeokuta         Saheed
15    Male   Abeokuta       Kehinde
16    Male   Abeokuta        Oluwole
17    Male      Lagos         Samuel
18    Male   Abeokuta        Ademola
19    Male     kobape         Victor
20    Male  Abeokuta          Sherif
21    Male   Abeokuta          Ayuba
22    Male     Ibadan          Hamid
23    Male   Abeokuta        Olajide
24    Male   Abeokuta        Solomon
25    Male      Sango  Oluwadamilare
26    Male  Cape Town      Oluwaseyi
27  Female   abeokuta         Adeoye
28    Male   Abeokuta      Babatunde
29    Male   Abeokuta         Samuel
30    Male   Abeokuta        Gabriel
31    Male   Abeokuta    Ridwanullah
32    Male   Abeokuta    Oluwapelumi
33    Male   Abeokuta        Michael

Cell Selection

In [91]:
# selecting a single cell
df["First Name"][0]

# another method of selecting cells using .at
df.at[0, "City"]

# another method of selecting cells using .iat
df.iat[10, 1]

'Deborah'

Row selection

`iloc` is used to select rows/columns or rows and column using index slicing.
This is very useful especially when your data bset do not have labels(that is, row names and column names)

In [92]:
# selecting some rows
df.iloc[0:7] # starts from the zero index and stops at the 6th element

,Timestamp,First Name,Last Name,Course Track,City,Gender,Seat Number,PC-Make,PC - OS,Feedback
0,2025-09-11 12:55:34-01:00,Peter,Okonmah,AI,Ogun,Male,28,MACBOOK,Mac OS,non
1,2025-09-11 12:56:11-01:00,Toyeebat,Nababa,AI,Abeokuta,Female,24,HP,Windows,Excellent
2,2025-09-11 12:57:08-01:00,Perpetual,Meninwa,AI,Lagos,Female,22,HP,Windows,Thank you so much for the opportunity.
3,2025-09-11 12:57:56-01:00,Mahfuz,Abdulhameed,AI,Abeokuta,Male,44,HP,Windows,Amazing Shit
4,2025-09-11 12:58:41-01:00,Divine,Gbadamosi,AI,Abeokuta,Male,35,DELL,Windows,Brain Racking
5,2025-09-11 12:58:55-01:00,Abdulmalik,Adedotun,AI,Abeokuta,Male,200,HP,Windows,Enjoying the course so far
6,2025-09-11 12:58:55-01:00,Naheemot,Adebiyi,AI,Abeokuta,Female,32,DELL,Windows,Grateful for the opportunity to be here.

In [93]:
# combination of row and column selection
df.iloc[0:5, 0:4]#the first slice picks the rows (0-4) and the second slice prints column(0-3)

                  Timestamp First Name    Last Name Course Track
0 2025-09-11 12:55:34-01:00      Peter      Okonmah           AI
1 2025-09-11 12:56:11-01:00   Toyeebat       Nababa           AI
2 2025-09-11 12:57:08-01:00  Perpetual      Meninwa           AI
3 2025-09-11 12:57:56-01:00     Mahfuz  Abdulhameed           AI
4 2025-09-11 12:58:41-01:00     Divine    Gbadamosi           AI



**Difference between `loc` and `iloc`**
- `loc` is label based(prints the first and last element specified) and `iloc` is index based (Uses zero index, prints the first element but doesn't print the last element specified)
- `loc` doesn't allow comnbination of rows and columns, `iloc` allows.

In [94]:
# using iloc()

df.loc[7:] #prints the seventh to the last element
df.loc[:7] #prints the 0th to the last element

df.loc[::]

,Timestamp,First Name,Last Name,Course Track,City,Gender,Seat Number,PC-Make,PC - OS,Feedback
0,2025-09-11 12:55:34-01:00,Peter,Okonmah,AI,Ogun,Male,28,MACBOOK,Mac OS,non
1,2025-09-11 12:56:11-01:00,Toyeebat,Nababa,AI,Abeokuta,Female,24,HP,Windows,Excellent
2,2025-09-11 12:57:08-01:00,Perpetual,Meninwa,AI,Lagos,Female,22,HP,Windows,Thank you so much for the opportunity.
3,2025-09-11 12:57:56-01:00,Mahfuz,Abdulhameed,AI,Abeokuta,Male,44,HP,Windows,Amazing Shit
4,2025-09-11 12:58:41-01:00,Divine,Gbadamosi,AI,Abeokuta,Male,35,DELL,Windows,Brain Racking
5,2025-09-11 12:58:55-01:00,Abdulmalik,Adedotun,AI,Abeokuta,Male,200,HP,Windows,Enjoying the course so far
6,2025-09-11 12:58:55-01:00,Naheemot,Adebiyi,AI,Abeokuta,Female,32,DELL,Windows,Grateful for the opportunity to be here.
7,2025-09-11 12:59:00-01:00,Kanyisola,Fagbayi,AI;Data Science,Lagos,Female,82,HP,Windows,One chin chin for you for this form
8,2025-09-11 12:59:16-01:00,Blessing,James,Cyber Security,Nairobi,Female,45678,HP,Windows,Thanks for creating the form.
9,2025-09-11 12:59:28-01:00,Hannah,Tanimola,AI,Abeokuta,Male,30,HP,Windows,On God
10,2025-09-11 12:59:41-01:00,Deborah,Adelegan,AI;Data Science,Abeokuta,Female,1,HP,Windows,None for now
11,2025-09-11 12:59:43-01:00,Esther,Kudoro,AI,Abeokuta,Female,1,HP,Windows,Chill
12,2025-09-11 13:00:03-01:00,Opeyemi,Odejimi,Cloud Computing,Abeokuta,Male,38,HP,Linux,Na wa
13,2025-09-11 13:00:13-01:00,Olasunkanmi,Rasak,AI,Kobape,Male,3,HP,Windows,My gratitude to the sponsor of this program an...
14,2025-09-11 13:00:27-01:00,Saheed,Olayinka,AI;Data Science;Web Dev,Abeokuta,Male,29,HP,Windows,None for now
15,2025-09-11 13:00:31-01:00,Kehinde,Akindele,Cloud Computing,Abeokuta,Male,54,Gateway,Windows,Great
16,2025-09-11 13:00:43-01:00,Oluwole,Oludayo,AI,Abeokuta,Male,9,HP,Windows,Good training to attend
17,2025-09-11 13:00:49-01:00,Samuel,Oyewusi,Web Dev,Lagos,Male,15,HP,Windows,Satisfactory
18,2025-09-11 13:00:54-01:00,Ademola,Akinrinde,AI,Abeokuta,Male,100,MACBOOK,Mac OS,Awesome shit\n\n
19,2025-09-11 13:01:31-01:00,Victor,Ademuyiwa,AI,kobape,Male,2,ASUS,Windows,Feels good
20,2025-09-11 13:01:44-01:00,Sherif,Okemakinde,AI,Abeokuta,Male,27,HP,Windows,Form filled
21,2025-09-11 13:01:46-01:00,Ayuba,Raji,AI,Abeokuta,Male,26,HP,Windows,None for now
22,2025-09-11 13:01:54-01:00,Hamid,Jimoh,AI,Ibadan,Male,299,DELL,Windows,I am curious
23,2025-09-11 13:02:28-01:00,Olajide,Abioye,AI,Abeokuta,Male,5,HP,Windows,"So far, i getting to familarize myself with nu..."
24,2025-09-11 13:02:49-01:00,Solomon,Olaiya,AI,Abeokuta,Male,16,MACBOOK,Mac OS,Delighted learning here
25,2025-09-11 13:02:56-01:00,Oluwadamilare,Bello,AI,Sango,Male,373,DELL;HP;LENOVO;MACBOOK;ASUS;,Mac OS,Coding is interesting when you understand
26,2025-09-11 13:02:59-01:00,Oluwaseyi,Egunjobi,Cloud Computing,Cape Town,Male,35,MACBOOK,Mac OS,Nice to meet you all
27,2025-09-11 13:03:12-01:00,Adeoye,Mary,AI,abeokuta,Female,15,LENOVO,Windows,Still processing
28,2025-09-11 13:03:36-01:00,Babatunde,Rahmon,AI,Abeokuta,Male,20,none,Windows,i actually have a pc that has a very low stora...
29,2025-09-11 13:06:03-01:00,Samuel,Dasaolu,AI,Abeokuta,Male,100,HP;MACBOOK,Linux,"Good so far, i guess"
30,2025-09-11 13:06:48-01:00,Gabriel,Bamgbose,AI,Abeokuta,Male,2,HP,Windows,Good
31,2025-09-11 13:10:16-01:00,Ridwanullah,Osho,AI;Cyber Security;Data Science,Abeokuta,Male,45,DELL,Windows,IT IS WHAT IT IS !!!
32,2025-09-11 13:11:39-01:00,Oluwapelumi,Adenuga,Web Dev,Abeokuta,Male,36,HP,Windows,live yours
33,2025-09-11 13:18:15-01:00,Michael,Osisami,AI,Abeokuta,Male,12,DELL;HP,Windows,Nil

Conditional Filtering

In [95]:
# filter rows where Gender is Male
filtered_male = df[df["Gender"] == "Male"]
print("Rows where Gender is Male")
filtered_male

# filter rows where Course Track is AI
filtered_course = df[df["Course Track"] == "AI"]
replaced_course = filtered_course.replace("AI", "Cybersecurity")
print("Rows where Course Track is AI")
replaced_course


# filter rows where PC-Make is Macbook or Dell
pc_make = df[(df["PC-Make"]== "MACBOOK") & (df["PC - OS"]== "Mac OS")]
print("rows where PC-Make is  or Dell")
pc_make


# Filter rows where City is either 'Lagos' or 'Abeokutaa'
cities = ['Lagos', 'Abeokuta']
city_filtered = df[df['City'].isin(cities)]
print("Rows where City is either 'Lagos' or 'Abeokuta':")
city_filtered

Rows where Gender is Male
Rows where Course Track is AI
rows where PC-Make is  or Dell
Rows where City is either 'Lagos' or 'Abeokuta':

,Timestamp,First Name,Last Name,Course Track,City,Gender,Seat Number,PC-Make,PC - OS,Feedback
1,2025-09-11 12:56:11-01:00,Toyeebat,Nababa,AI,Abeokuta,Female,24,HP,Windows,Excellent
2,2025-09-11 12:57:08-01:00,Perpetual,Meninwa,AI,Lagos,Female,22,HP,Windows,Thank you so much for the opportunity.
3,2025-09-11 12:57:56-01:00,Mahfuz,Abdulhameed,AI,Abeokuta,Male,44,HP,Windows,Amazing Shit
4,2025-09-11 12:58:41-01:00,Divine,Gbadamosi,AI,Abeokuta,Male,35,DELL,Windows,Brain Racking
5,2025-09-11 12:58:55-01:00,Abdulmalik,Adedotun,AI,Abeokuta,Male,200,HP,Windows,Enjoying the course so far
6,2025-09-11 12:58:55-01:00,Naheemot,Adebiyi,AI,Abeokuta,Female,32,DELL,Windows,Grateful for the opportunity to be here.
7,2025-09-11 12:59:00-01:00,Kanyisola,Fagbayi,AI;Data Science,Lagos,Female,82,HP,Windows,One chin chin for you for this form
9,2025-09-11 12:59:28-01:00,Hannah,Tanimola,AI,Abeokuta,Male,30,HP,Windows,On God
10,2025-09-11 12:59:41-01:00,Deborah,Adelegan,AI;Data Science,Abeokuta,Female,1,HP,Windows,None for now
11,2025-09-11 12:59:43-01:00,Esther,Kudoro,AI,Abeokuta,Female,1,HP,Windows,Chill
12,2025-09-11 13:00:03-01:00,Opeyemi,Odejimi,Cloud Computing,Abeokuta,Male,38,HP,Linux,Na wa
14,2025-09-11 13:00:27-01:00,Saheed,Olayinka,AI;Data Science;Web Dev,Abeokuta,Male,29,HP,Windows,None for now
15,2025-09-11 13:00:31-01:00,Kehinde,Akindele,Cloud Computing,Abeokuta,Male,54,Gateway,Windows,Great
16,2025-09-11 13:00:43-01:00,Oluwole,Oludayo,AI,Abeokuta,Male,9,HP,Windows,Good training to attend
17,2025-09-11 13:00:49-01:00,Samuel,Oyewusi,Web Dev,Lagos,Male,15,HP,Windows,Satisfactory
18,2025-09-11 13:00:54-01:00,Ademola,Akinrinde,AI,Abeokuta,Male,100,MACBOOK,Mac OS,Awesome shit\n\n
21,2025-09-11 13:01:46-01:00,Ayuba,Raji,AI,Abeokuta,Male,26,HP,Windows,None for now
23,2025-09-11 13:02:28-01:00,Olajide,Abioye,AI,Abeokuta,Male,5,HP,Windows,"So far, i getting to familarize myself with nu..."
24,2025-09-11 13:02:49-01:00,Solomon,Olaiya,AI,Abeokuta,Male,16,MACBOOK,Mac OS,Delighted learning here
28,2025-09-11 13:03:36-01:00,Babatunde,Rahmon,AI,Abeokuta,Male,20,none,Windows,i actually have a pc that has a very low stora...
29,2025-09-11 13:06:03-01:00,Samuel,Dasaolu,AI,Abeokuta,Male,100,HP;MACBOOK,Linux,"Good so far, i guess"
30,2025-09-11 13:06:48-01:00,Gabriel,Bamgbose,AI,Abeokuta,Male,2,HP,Windows,Good
31,2025-09-11 13:10:16-01:00,Ridwanullah,Osho,AI;Cyber Security;Data Science,Abeokuta,Male,45,DELL,Windows,IT IS WHAT IT IS !!!
32,2025-09-11 13:11:39-01:00,Oluwapelumi,Adenuga,Web Dev,Abeokuta,Male,36,HP,Windows,live yours
33,2025-09-11 13:18:15-01:00,Michael,Osisami,AI,Abeokuta,Male,12,DELL;HP,Windows,Nil

Using the .query() method

In [ ]:
df = pd.read_csv("bio_data.csv")
# use query to filter rows where Course Track is " AI" and Feedback is "Excellent"
query_filtered = df.query("Gender == 'Female' and Feedback == 'Excellent' ")
print("Rows filtered using query() method:")
query_filtered

# Filter rows where Course_Track is 'Data Science'
# cyber_security = df.query("CourseTrack == 'Cyber Security' ")
# print("Students in the Cyber Security track:")
# cyber_security


seat_number = df.query("Seat Number > 6 and Gender == 'Female'")

Rows filtered using query() method:

,Timestamp,First Name,Last Name,Course Track,City,Gender,Seat Number,PC-Make,PC - OS,Feedback
1,2025/09/11 12:56:11 PM GMT+1,Toyeebat,Nababa,AI,Abeokuta,Female,24,HP,Windows,Excellent

In [107]:
df["Seat Number"].dtypes

dtype('O')